In [31]:
import time, json, requests
from pathlib import Path
from bs4 import BeautifulSoup, Tag
import pandas as pd
from tqdm import tqdm          # ← plain, widget‑free

In [7]:
# Get a list of all .xlsx files in the current directory
xlsx_files = glob.glob("*.xlsx")

# Read each file and add a column for the filename
df_list = []
for file in xlsx_files:
    df = pd.read_excel(file)
    df['election'] = os.path.splitext(os.path.basename(file))[0]  # remove .xlsx
    df_list.append(df)

# Combine all dataframes into one
combined_df = pd.concat(df_list, ignore_index=True)

In [8]:
combined_df.to_csv('all_candidates_national_elections_bangladesh.csv')

In [44]:
combined_df.loc[:, 'URL'] = combined_df['ID'].apply(lambda x: f"http://www.votebd.org/candidates/?candidate={x}")

In [52]:
# Ensure 'HTML' directory exists
html_folder = Path("HTML")
html_folder.mkdir(exist_ok=True)

# Iterate through each URL in combined_df
for idx, row in combined_df.iterrows():
    url = row['URL']
    candidate_id = row['ID']
    filename = html_folder / f"{candidate_id}.html"

    # Skip if file already exists
    if filename.exists():
        print(f"Already downloaded: {filename}")
        continue

    try:
        print(f"Fetching: {url}")
        response = requests.get(url, timeout=10)
        response.raise_for_status()

        with open(filename, "w", encoding='utf-8') as f:
            f.write(response.text)
        print(f"Saved: {filename}")

    except requests.RequestException as e:
        print(f"Error fetching {url}: {e}")

    time.sleep(15)

Fetching: http://www.votebd.org/candidates/?candidate=56a62dc4e19b40c27fbd6c80
Saved: HTML/56a62dc4e19b40c27fbd6c80.html
Fetching: http://www.votebd.org/candidates/?candidate=56a62dc4e19b40c27fbd6c77
Saved: HTML/56a62dc4e19b40c27fbd6c77.html
Fetching: http://www.votebd.org/candidates/?candidate=56a62dc4e19b40c27fbd6c78
Saved: HTML/56a62dc4e19b40c27fbd6c78.html
Fetching: http://www.votebd.org/candidates/?candidate=56a62dc4e19b40c27fbd6c79
Saved: HTML/56a62dc4e19b40c27fbd6c79.html
Fetching: http://www.votebd.org/candidates/?candidate=56a62dc4e19b40c27fbd6c7b
Saved: HTML/56a62dc4e19b40c27fbd6c7b.html
Fetching: http://www.votebd.org/candidates/?candidate=56a62dc4e19b40c27fbd6bcd
Saved: HTML/56a62dc4e19b40c27fbd6bcd.html

KeyboardInterrupt:

In [76]:
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

def extract_nested_data(cell, labels=None):
    """Return dict if nested table matches labels; else return flattened string."""
    if cell.find('table'):
        values = [td.get_text(strip=True) for td in cell.find_all('td')]
        if labels and len(values) == len(labels):
            return dict(zip(labels, values))
        return ' | '.join(values)
    return cell.get_text(strip=True)

# Target columns to keep per election
base_fields = ["প্রার্থীর পদ", "পার্টির নাম", "প্রার্থিতা", "আয়", "সম্পদ/নিট সম্পদ", "ঋণ", "দায়", "কর"]

html_folder = Path("HTML")
flattened_records = []

for file in html_folder.glob("*.html"):
    with open(file, "r", encoding="utf-8") as f:
        soup = BeautifulSoup(f, "html.parser")
        table = soup.find("table", class_="table table-bordered table-hover")
        if not table:
            continue

        thead = table.find("thead")
        headers = [th.get_text(strip=True) for th in thead.find_all("th")]
        rows = table.find("tbody").find_all("tr", recursive=False)

        # Skip header rows or invalid ones
        for tr in rows:
            tds = tr.find_all("td", recursive=False)
            if len(tds) != len(headers):
                continue

            row_data = {}
            for i, td in enumerate(tds):
                header = headers[i]
                if header == "আয়":
                    value = extract_nested_data(td, labels=["নিজের", "নির্ভরশীল", "মোট"])
                elif header == "সম্পদ/নিট সম্পদ":
                    value = extract_nested_data(td, labels=["নিজের", "নির্ভরশীল", "স্বামী স্ত্রী মোট"])
                else:
                    value = extract_nested_data(td)
                row_data[header] = value

            election = row_data.get("নির্বাচন", "অজানা নির্বাচন")
            record = {"source_file": file.name}

            for field in base_fields:
                if field in row_data:
                    key = f"{election}_{field}"
                    record[key] = row_data[field]

            flattened_records.append(record)

# Create DataFrame
df_long = pd.DataFrame(flattened_records)

# Pivot: one row per candidate (source_file)
df_pivoted = df_long.groupby("source_file").first().reset_index()
df_pivoted

,source_file,দশম জাতীয় সংসদ নির্বাচন ২০১৪_প্রার্থীর পদ,দশম জাতীয় সংসদ নির্বাচন ২০১৪_পার্টির নাম,দশম জাতীয় সংসদ নির্বাচন ২০১৪_প্রার্থিতা,দশম জাতীয় সংসদ নির্বাচন ২০১৪_আয়,দশম জাতীয় সংসদ নির্বাচন ২০১৪_সম্পদ/নিট সম্পদ,দশম জাতীয় সংসদ নির্বাচন ২০১৪_ঋণ,দশম জাতীয় সংসদ নির্বাচন ২০১৪_দায়,দশম জাতীয় সংসদ নির্বাচন ২০১৪_কর,নবম জাতীয় সংসদ নির্বাচন ২০০৮_প্রার্থীর পদ,...,একাদশ জাতীয় সংসদ নির্বাচন ২০১৮_দায়,একাদশ জাতীয় সংসদ নির্বাচন ২০১৮_কর,দ্বাদশ জাতীয় সংসদ নির্বাচন ২০২৪_প্রার্থীর পদ,দ্বাদশ জাতীয় সংসদ নির্বাচন ২০২৪_পার্টির নাম,দ্বাদশ জাতীয় সংসদ নির্বাচন ২০২৪_প্রার্থিতা,দ্বাদশ জাতীয় সংসদ নির্বাচন ২০২৪_আয়,দ্বাদশ জাতীয় সংসদ নির্বাচন ২০২৪_সম্পদ/নিট সম্পদ,দ্বাদশ জাতীয় সংসদ নির্বাচন ২০২৪_ঋণ,দ্বাদশ জাতীয় সংসদ নির্বাচন ২০২৪_দায়,দ্বাদশ জাতীয় সংসদ নির্বাচন ২০২৪_কর
0,56a62dc4e19b40c27fbd6bcd.html,সংসদ সদস্য,বাংলাদেশ আওয়ামী লীগ,নির্বাচিত,"{'নিজের': '৪১৭২৩০৬', 'নির্ভরশীল': '০', 'মোট': ...","{'নিজের': '১৪৬৬৭৭৬৯', 'নির্ভরশীল': '০', 'স্বাম...",,০,১৫৮৭৩৯,সংসদ সদস্য,...,,,সংসদ সদস্য,বাংলাদেশ আওয়ামী লীগ,,"{'নিজের': '৩৮২৭৯৮৫', 'নির্ভরশীল': '০', 'মোট': ...","{'নিজের': '৭৯৭২২২৯১', 'নির্ভরশীল': '০', 'স্বাম...",,,
1,56a62dc4e19b40c27fbd6c77.html,সংসদ সদস্য,জাতীয় পার্টি-জেপি,অনির্বাচিত,"{'নিজের': '২৫০০০০', 'নির্ভরশীল': '০', 'মোট': '...","{'নিজের': '১৯৩০০০০', 'নির্ভরশীল': '০', 'স্বামী...",,০,,None,...,None,None,None,None,None,None,None,None,None,None
2,56a62dc4e19b40c27fbd6c78.html,সংসদ সদস্য,স্বতন্ত্র,অনির্বাচিত,"{'নিজের': '২৪০৯৪৭৫', 'নির্ভরশীল': '০', 'মোট': ...","{'নিজের': '২৬৫৬৬১৩৩', 'নির্ভরশীল': '০', 'স্বাম...",,৩২৫৫৬১,১৮৭৬৩১,সংসদ সদস্য,...,,৮৩৭৭৭,সংসদ সদস্য,বাংলাদেশ আওয়ামী লীগ,নির্বাচিত,"{'নিজের': '৫৫০৪৮৪', 'নির্ভরশীল': '০', 'মোট': '...","{'নিজের': '১৮১৯২১৭১১', 'নির্ভরশীল': '০', 'স্বা...",,৬৬৯০২৯৫৬,
3,56a62dc4e19b40c27fbd6c79.html,সংসদ সদস্য,বাংলাদেশ আওয়ামী লীগ,নির্বাচিত,"{'নিজের': '১২২০০০০', 'নির্ভরশীল': '০', 'মোট': ...","{'নিজের': '৭১৫২২৭৮', 'নির্ভরশীল': '০', 'স্বামী...",,৭৩৫১৭২,১৫০০০০,None,...,None,None,None,None,None,None,None,None,None,None
4,56a62dc4e19b40c27fbd6c7b.html,সংসদ সদস্য,জাতীয় সমাজতান্ত্রিক দল-জাসদ,অনির্বাচিত,"{'নিজের': '২০০০০০', 'নির্ভরশীল': '৩০০০', 'মোট'...","{'নিজের': '২১৭৮০০০০', 'নির্ভরশীল': '০', 'স্বাম...",,০,,None,...,None,None,None,None,None,None,None,None,None,None
5,56a62dc4e19b40c27fbd6c80.html,সংসদ সদস্য,স্বতন্ত্র,অনির্বাচিত,"{'নিজের': '২৫০০০০', 'নির্ভরশীল': '০', 'মোট': '...","{'নিজের': '১৫৭৯৩৬০০', 'নির্ভরশীল': '০', 'স্বাম...",৪৭০০০০০০০,০,৫০০০,None,...,None,None,None,None,None,None,None,None,None,None

In [73]:
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

html_folder = Path("HTML")
records = []

for file in html_folder.glob("*.html"):
    with open(file, "r", encoding="utf-8") as f:
        soup = BeautifulSoup(f, "html.parser")
        tables = soup.find_all("table", class_="table table-bordered")

        target_table = None
        for table in tables:
            if "table-hover" in table.get("class", []):
                continue

            rows = table.find_all("tr")
            valid_rows = [tr for tr in rows if len(tr.find_all("td", recursive=False)) == 2]
            # Heuristic: if most rows are 2-td rows, it's probably the one we want
            if len(valid_rows) >= 3:
                target_table = table
                break

        if not target_table:
            print(f"❌ No 2-col table found in {file.name}")
            continue

        record = {}
        for tr in target_table.find_all("tr"):
            tds = tr.find_all("td", recursive=False)
            if len(tds) != 2:
                continue

            label = tds[0].get_text(separator=" ", strip=True).rstrip(":：।").strip()
            value = tds[1].get_text(strip=True)
            record[label] = value

        if record:
            record["source_file"] = file.name
            records.append(record)

df_kv_fixed = pd.DataFrame(records)
df_kv_fixed

,আমি (প্রার্থীর নাম),জন্ম তারিখ,পিতা / স্বামীর নাম,মাতার নাম,ঠিকানা,এর আসন থেকে : নাম এবং নির্বাচনী এলাকা সংখ্যা,source_file
0,মো: আইয়ুব আলী (ফনু),,মৃত আঃ রউফ মুন্সি,মৃত আম্বিয়া খাতুন,"নিউটাউন বিলপাড়, নেত্রকোনা, পো: নেত্রকোনা-২৪০০...","১৫৮, নেত্রকোনা-২, নেত্রকোণা সদর ও বারহাট্টা উপ...",56a62dc4e19b40c27fbd6c77.html
1,আবু সালেহ মোঃ মনিরুল ইসলাম,,মৃত আব্দুল মোমেন,মমতাজ বেগম,গ্রামঃ কালীর বাজার ডাকঘরঃ শেরপুর শহর উপজেলাঃ শ...,"১৪৩, শেরপুর-১",56a62dc4e19b40c27fbd6c7b.html
2,আরিফ খান জয়,,মৃত মোঃ আব্দুস ছাত্তার খান,মৃত তমজিদা খানম,"সাং- নিউটাউন, পোঃ নেত্রকোণা, থানা- নেত্রকোণা স...","১৫৮, নেত্রকোণা-২",56a62dc4e19b40c27fbd6c79.html
3,আব্দুন নুর খান,,মৃত: আব্দুল আজিজ খান,আয়েশা আক্তার খানম,"গ্রাম- কাটলী, ডাকঘর-নেত্রকোণা, থানা-নেত্রকোণা,...","১৫৮, নেত্রকোনা-২",56a62dc4e19b40c27fbd6c80.html
4,মোশতাক আহম্মেদ রুহী,1974-06-19,প্রফেসর মুজিবর রহমান,আনোয়ারা রহমান,"চত্রংপুর, চাঁনপুর, ডাকঘর-কলমাকান্দা-১৪৩০, কলমা...","১৫৭, নেত্রকোনা-১, দুর্গাপুর, কলমাকান্দা",56a62dc4e19b40c27fbd6c78.html
5,মো: মোসলেম উদ্দিন,,মৃত শুকুর মাহমুদ মুন্সী,মৃত আয়মন বেগম,"গ্রাম: নিউনী, কুশমাইল, ফুলবাড়ীয়া, ময়মনসিংহ","১৫১, ময়মনসিংহ-৬",56a62dc4e19b40c27fbd6bcd.html

In [78]:
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

html_folder = Path("HTML")
records = []

for file in html_folder.glob("*.html"):
    with open(file, "r", encoding="utf-8") as f:
        soup = BeautifulSoup(f, "html.parser")
        tables = soup.find_all("table", class_="table table-bordered")

        for table in tables:
            rows = table.find_all("tr")
            if not rows or len(rows[0].find_all(["th", "td"])) != 4:
                continue

            headers = [th.get_text(strip=True) for th in rows[0].find_all(["th", "td"])]
            if "আয়ের উৎসের বিবরণ" in headers and "প্রার্থীদের এই খাত থেকে বার্ষিক আয়" in headers:
                income_dict = {"source_file": file.name}

                for tr in rows[1:]:
                    tds = tr.find_all("td")
                    if len(tds) != 4:
                        continue

                    income_type = tds[1].get_text(strip=True)
                    own_income = tds[2].get_text(strip=True)
                    dep_income = tds[3].get_text(strip=True)

                    if income_type:
                        income_dict[f"{income_type}_প্রার্থীদের এই খাত থেকে বার্ষিক আয়"] = own_income
                        income_dict[f"{income_type}_প্রার্থীর উপর নির্ভরশীলদের আয়"] = dep_income

                records.append(income_dict)
                break  # only one income table per file

# Create wide-format DataFrame
df_income_wide = pd.DataFrame(records)

df_income_wide

,source_file,business_প্রার্থীদের এই খাত থেকে বার্ষিক আয়,business_প্রার্থীর উপর নির্ভরশীলদের আয়,building_fare_প্রার্থীদের এই খাত থেকে বার্ষিক আয়,building_fare_প্রার্থীর উপর নির্ভরশীলদের আয়,agriculture_প্রার্থীদের এই খাত থেকে বার্ষিক আয়,agriculture_প্রার্থীর উপর নির্ভরশীলদের আয়,service_প্রার্থীদের এই খাত থেকে বার্ষিক আয়,service_প্রার্থীর উপর নির্ভরশীলদের আয়,profession_প্রার্থীদের এই খাত থেকে বার্ষিক আয়,profession_প্রার্থীর উপর নির্ভরশীলদের আয়,shares_প্রার্থীদের এই খাত থেকে বার্ষিক আয়,shares_প্রার্থীর উপর নির্ভরশীলদের আয়,others_প্রার্থীদের এই খাত থেকে বার্ষিক আয়,others_প্রার্থীর উপর নির্ভরশীলদের আয়
0,56a62dc4e19b40c27fbd6c77.html,120000,,90000,,40000,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,56a62dc4e19b40c27fbd6c7b.html,NaN,NaN,40000,,40000,,120000,,NaN,NaN,NaN,NaN,NaN,NaN
2,56a62dc4e19b40c27fbd6c79.html,NaN,NaN,NaN,NaN,40000,,460350,,276998,,442652,,NaN,NaN
3,56a62dc4e19b40c27fbd6c80.html,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250000,
4,56a62dc4e19b40c27fbd6c78.html,813244,,78740,,59409,,330000,,89132,,NaN,NaN,1038950,
5,56a62dc4e19b40c27fbd6bcd.html,NaN,NaN,NaN,NaN,27306,,330000,,795000,,NaN,NaN,3020000,

In [79]:
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

html_folder = Path("HTML")
asset_records = []

for file in html_folder.glob("*.html"):
    with open(file, "r", encoding="utf-8") as f:
        soup = BeautifulSoup(f, "html.parser")
        tables = soup.find_all("table", class_="table table-bordered")

        for table in tables:
            rows = table.find_all("tr")
            if not rows or len(rows[0].find_all(["th", "td"])) < 7:
                continue

            header_texts = [th.get_text(strip=True) for th in rows[0].find_all(["th", "td"])]
            if "সম্পদের বিবরণ" in header_texts and "নিজের নাম (মূল্য)" in header_texts:
                asset_dict = {"source_file": file.name}
                headers = header_texts[2:]  # skip first two (index and asset type)

                for tr in rows[1:]:
                    tds = tr.find_all("td")
                    if len(tds) < 3:
                        continue  # must have at least asset name and one value

                    asset_type = tds[1].get_text(strip=True)

                    for i, header in enumerate(headers):
                        idx = i + 2  # adjust for skipped index and asset_type
                        value = tds[idx].get_text(strip=True) if idx < len(tds) else ""
                        col_name = f"{asset_type}_{header}"
                        asset_dict[col_name] = value

                asset_records.append(asset_dict)
                break  # only one asset table per file

# Create wide-format DataFrame
df_asset_wide = pd.DataFrame(asset_records)

df_asset_wide

,source_file,cash_taka_নিজের নাম (মূল্য),cash_taka_নিজের নাম (পরিমাণ),cash_taka_স্ত্রী / স্বামীর নামে (পরিমাণ),cash_taka_স্ত্রী / স্বামীর নামে (মূল্য),cash_taka_নির্ভরশীলদের নামে (পরিমাণ),cash_taka_নির্ভরশীলদের নামে (মূল্য),bank_deposit_নিজের নাম (মূল্য),bank_deposit_নিজের নাম (পরিমাণ),bank_deposit_স্ত্রী / স্বামীর নামে (পরিমাণ),...,others_স্ত্রী / স্বামীর নামে (পরিমাণ),others_স্ত্রী / স্বামীর নামে (মূল্য),others_নির্ভরশীলদের নামে (পরিমাণ),others_নির্ভরশীলদের নামে (মূল্য),foreign_currency_নিজের নাম (মূল্য),foreign_currency_নিজের নাম (পরিমাণ),foreign_currency_স্ত্রী / স্বামীর নামে (পরিমাণ),foreign_currency_স্ত্রী / স্বামীর নামে (মূল্য),foreign_currency_নির্ভরশীলদের নামে (পরিমাণ),foreign_currency_নির্ভরশীলদের নামে (মূল্য)
0,56a62dc4e19b40c27fbd6c77.html,100000,,,,,,650000,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,56a62dc4e19b40c27fbd6c7b.html,500000,,,,,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,56a62dc4e19b40c27fbd6c79.html,1214278,,,,,,1700000,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,56a62dc4e19b40c27fbd6c80.html,763600,,,,,,NaN,NaN,NaN,...,,,,,NaN,NaN,NaN,NaN,NaN,NaN
4,56a62dc4e19b40c27fbd6c78.html,5149244,,,,,,7930448,,,...,,,,,25434,(৩৪৩.৭০ ডলার),,,,
5,56a62dc4e19b40c27fbd6bcd.html,4193652,,,,,,2319567,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

html_folder = Path("HTML")
extended_asset_records = []

for file in html_folder.glob("*.html"):
    with open(file, "r", encoding="utf-8") as f:
        soup = BeautifulSoup(f, "html.parser")
        tables = soup.find_all("table", class_="table table-bordered")

        for table in tables:
            rows = table.find_all("tr")
            if not rows or len(rows[0].find_all(["th", "td"])) < 7:
                continue

            header_texts = [th.get_text(strip=True) for th in rows[0].find_all(["th", "td"])]
            if "সম্পদের বিবরণ" in header_texts and "যৌথ মালিকানা (মূল্য)" in header_texts:
                asset_dict = {"source_file": file.name}
                headers = header_texts[2:]  # skip index and asset type

                for tr in rows[1:]:
                    tds = tr.find_all("td")
                    if len(tds) < 3:
                        continue  # must have at least asset name and one value

                    asset_type = tds[1].get_text(strip=True)

                    for i, header in enumerate(headers):
                        idx = i + 2  # adjust index (after ID and asset type)
                        value = tds[idx].get_text(strip=True) if idx < len(tds) else ""
                        col_name = f"{asset_type}_{header}"
                        asset_dict[col_name] = value

                extended_asset_records.append(asset_dict)
                break  # only one such table per file

# Create wide-format DataFrame
df_extended_assets = pd.DataFrame(extended_asset_records)

df_extended_assets

,source_file,cultivated_land_নিজের নাম (মূল্য),cultivated_land_নিজের নাম (পরিমাণ),cultivated_land_স্ত্রী / স্বামীর নামে (পরিমাণ),cultivated_land_স্ত্রী / স্বামীর নামে (মূল্য),cultivated_land_নির্ভরশীলদের নামে (পরিমাণ),cultivated_land_নির্ভরশীলদের নামে (মূল্য),cultivated_land_যৌথ মালিকানা (পরিমাণ),cultivated_land_যৌথ মালিকানা (মূল্য),cultivated_land_যৌথ মালিকানার ক্ষেত্রে প্রার্থীর অংশ (পরিমাণ),...,others_নিজের নাম (মূল্য),others_নিজের নাম (পরিমাণ),others_স্ত্রী / স্বামীর নামে (পরিমাণ),others_স্ত্রী / স্বামীর নামে (মূল্য),others_নির্ভরশীলদের নামে (পরিমাণ),others_নির্ভরশীলদের নামে (মূল্য),others_যৌথ মালিকানা (পরিমাণ),others_যৌথ মালিকানা (মূল্য),others_যৌথ মালিকানার ক্ষেত্রে প্রার্থীর অংশ (পরিমাণ),others_যৌথ মালিকানার ক্ষেত্রে প্রার্থীর অংশ (মূল্য)
0,56a62dc4e19b40c27fbd6c77.html,,,,,,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,56a62dc4e19b40c27fbd6c7b.html,5000000,১.০০ একর,,,,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,56a62dc4e19b40c27fbd6c79.html,200000,"১০০ শতক, ০.২৫ শতক",,,,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,56a62dc4e19b40c27fbd6c80.html,,,,,,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,56a62dc4e19b40c27fbd6c78.html,1563112,৪.৪৬ একর,,,,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,56a62dc4e19b40c27fbd6bcd.html,409750,২.০৫ একর,,,,,,,,...,3285000,,,,,,,,,

In [81]:
# Start with the main affidavit table
df_master = df_pivoted.copy()

# Sequential left joins by source_file
for df in [df_kv_fixed, df_income_wide, df_asset_wide, df_extended_assets]:
    df_master = df_master.merge(df, on="source_file", how="left")

df_master

,source_file,দশম জাতীয় সংসদ নির্বাচন ২০১৪_প্রার্থীর পদ,দশম জাতীয় সংসদ নির্বাচন ২০১৪_পার্টির নাম,দশম জাতীয় সংসদ নির্বাচন ২০১৪_প্রার্থিতা,দশম জাতীয় সংসদ নির্বাচন ২০১৪_আয়,দশম জাতীয় সংসদ নির্বাচন ২০১৪_সম্পদ/নিট সম্পদ,দশম জাতীয় সংসদ নির্বাচন ২০১৪_ঋণ,দশম জাতীয় সংসদ নির্বাচন ২০১৪_দায়,দশম জাতীয় সংসদ নির্বাচন ২০১৪_কর,নবম জাতীয় সংসদ নির্বাচন ২০০৮_প্রার্থীর পদ,...,others_নিজের নাম (মূল্য)_y,others_নিজের নাম (পরিমাণ)_y,others_স্ত্রী / স্বামীর নামে (পরিমাণ)_y,others_স্ত্রী / স্বামীর নামে (মূল্য)_y,others_নির্ভরশীলদের নামে (পরিমাণ)_y,others_নির্ভরশীলদের নামে (মূল্য)_y,others_যৌথ মালিকানা (পরিমাণ),others_যৌথ মালিকানা (মূল্য),others_যৌথ মালিকানার ক্ষেত্রে প্রার্থীর অংশ (পরিমাণ),others_যৌথ মালিকানার ক্ষেত্রে প্রার্থীর অংশ (মূল্য)
0,56a62dc4e19b40c27fbd6bcd.html,সংসদ সদস্য,বাংলাদেশ আওয়ামী লীগ,নির্বাচিত,"{'নিজের': '৪১৭২৩০৬', 'নির্ভরশীল': '০', 'মোট': ...","{'নিজের': '১৪৬৬৭৭৬৯', 'নির্ভরশীল': '০', 'স্বাম...",,০,১৫৮৭৩৯,সংসদ সদস্য,...,3285000,,,,,,,,,
1,56a62dc4e19b40c27fbd6c77.html,সংসদ সদস্য,জাতীয় পার্টি-জেপি,অনির্বাচিত,"{'নিজের': '২৫০০০০', 'নির্ভরশীল': '০', 'মোট': '...","{'নিজের': '১৯৩০০০০', 'নির্ভরশীল': '০', 'স্বামী...",,০,,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,56a62dc4e19b40c27fbd6c78.html,সংসদ সদস্য,স্বতন্ত্র,অনির্বাচিত,"{'নিজের': '২৪০৯৪৭৫', 'নির্ভরশীল': '০', 'মোট': ...","{'নিজের': '২৬৫৬৬১৩৩', 'নির্ভরশীল': '০', 'স্বাম...",,৩২৫৫৬১,১৮৭৬৩১,সংসদ সদস্য,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,56a62dc4e19b40c27fbd6c79.html,সংসদ সদস্য,বাংলাদেশ আওয়ামী লীগ,নির্বাচিত,"{'নিজের': '১২২০০০০', 'নির্ভরশীল': '০', 'মোট': ...","{'নিজের': '৭১৫২২৭৮', 'নির্ভরশীল': '০', 'স্বামী...",,৭৩৫১৭২,১৫০০০০,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,56a62dc4e19b40c27fbd6c7b.html,সংসদ সদস্য,জাতীয় সমাজতান্ত্রিক দল-জাসদ,অনির্বাচিত,"{'নিজের': '২০০০০০', 'নির্ভরশীল': '৩০০০', 'মোট'...","{'নিজের': '২১৭৮০০০০', 'নির্ভরশীল': '০', 'স্বাম...",,০,,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,56a62dc4e19b40c27fbd6c80.html,সংসদ সদস্য,স্বতন্ত্র,অনির্বাচিত,"{'নিজের': '২৫০০০০', 'নির্ভরশীল': '০', 'মোট': '...","{'নিজের': '১৫৭৯৩৬০০', 'নির্ভরশীল': '০', 'স্বাম...",৪৭০০০০০০০,০,৫০০০,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN